server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/bamboo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: r3i5e

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

#eureka:
#  instance:
#    instance-id: user-service
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

app:
  secret: test  #accessToken 암호화
  refresh-secret: test  #refreshToken 암호화
  client-id: 695708fb9dae4801993f0ec68cad7c620d0701eea5444d199c00b39ed67f5a7c
  client-secret: c53e942274cc4e41977271cf3c32b41463f9e6c48e684f92b58564686ec5243b
  auth-url: http://dauth.b1nd.com/api
  open-api-url: http://open.dodam.b1nd.com/api
jwt:
  access:
    expire: 1000 * 60 * 60 * 24
  refresh:
    expire: 1000 * 60 * 60 * 24 * 7