server:
  port: 7001

spring:
  application:
    name: post
  profiles:
    active: config
  config:
    import: optional:configserver:http://52.79.253.78:8888
  datasource:
    url: jdbc:mysql://test.cufa7phrrtky.ap-northeast-2.rds.amazonaws.com:3306/bamboo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bamboobackend
    password: Bamboobackend12!!


  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: post-service
  client:
    service-url:
      defaultZone: http://52.79.253.78:8761/eureka
    fetch-registry: true
    register-with-eureka: true

