spring:
  application:
    name: user
  profiles:
    active: config
  config:
    import: optional:configserver:http://13.209.33.18:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  packages-to-scan: com.bamboo.userserivce