server:
  port: 8765

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false # eureka? registry? ???? ??? ??, ???? ???
    fetch-registry: false # registry? ?? ??? ???? ??? ??