server:
  port: ${PORT}
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/bamboo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: admin-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

