<<<<<<< HEAD
=======
server:
  port: 8081

>>>>>>> fdeaf202516cee6a8cb09b706cf78736e0cb2f44
spring:
  application:
    name: gateway
  profiles:
    active: config
  config:
    import: optional:configserver:http://43.200.66.133:8888
