server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "https://www.daesoup.com/"
            allowedHeaders: "Authorization"
            allowedMethods: "*"
            allow-credentials: false
            max-age: 30
#      routes:
#        - id: user-service
#          uri: http://3.35.127.40:7000/
#          predicates:
#            - name: Path
#              args:
#                patterns: /user/**
#        - id: post-service
#          uri: http://3.35.240.224:7001/
#          predicates:
#            - name: Path
#              args:
#                patterns: /post/**
#            - Method=GET
#        - id: post-service
#          uri: http://3.35.240.224:7001/
#          predicates:
#            - name: Path
#              args:
#                patterns: /post/**
#            - Method=POST
#          filters:
#            - AuthorizationHeaderFilter
#        - id: admin-service
#          uri: http://15.164.199.85:7003/
#          predicates:
#            - name: Path
#              args:
#                patterns: /admin/**
#            - Method=POST
#          filters:
#            - AuthorizationHeaderFilter
#        - id: upload-service
#          uri: http://3.37.68.115:7005/
#          predicates:
#            - name: Path
#              args:
#                patterns: /upload/**
#            - Method=POST
#          filters:
#            - AuthorizationHeaderFilter
#        - id: comment-service
#          uri: http://43.201.169.169:7004/
#          predicates:
#            - name: Path
#              args:
#                patterns: /comment/**
#            - Method=POST
#          filters:
#            - AuthorizationHeaderFilter

eureka:
  instance:
    instance-id: apigateway-service
  client:
    service-url:
      defaultZone: http://43.200.66.133:8761/eureka
    fetch-registry: true
    register-with-eureka: true