server:
  port: 8080

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#            allow-credentials: true
      routes:
        - id: user-service
          uri: http://3.36.150.248:7000
          predicates:
            - name: Path
              args:
                patterns: /user/**
          metadata:
            cors
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
            maxAge: 30
        - id: post-service
          uri: http://3.36.150.248:7001
          predicates:
            - name: Path
              args:
                patterns: /post/**
          metadata:
            cors
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
            maxAge: 30
#            maxAge: 30
#            - name: Method
#              args:
#                methods:
#                  - POST
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: recruitlist
#                fallbackUri: forward:/fallbacks/7
#            - name: RewritePath
#              args:
#                regexp: /user-service/(?<path>.*)
#                replacement: /$\{path}
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        - id: post-service
#          uri: lb://POST-SERVICE
#          predicates:
#            - Path=/post-service/
#            - Method=POST
#          filters:
#            - RemoveRequestHeader-Cookie
#            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
#        - id: upload-service
#            uri: lb://UPLOAD-SERVICE
#            predicates:
#              - Path=/upload-service/
#              - Method=POST
#            filters:
#              - RemoveRequestHeader-Cookie
#              - RewritePath=/upload-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.209.33.18:8761/eureka